Choose_language = 'Please choose language./Пожалуйста выберите язык. (English/Русский): '
language1 = 'English'
language2 = 'Русский'
langError = 'Error! There is no language in the database! Please try again. '

Choose_individual1 = 'Personal, family, single parent? Enter with a small letter. '
Read_monthly_income1 = 'Further please enter your annual income (in USD). '
p1 = 'personal'
f1 = 'family'
sp1 = 'single parent'
question1 = 'What is your monthly income in'

Choose_individual2 = 'Один субъект,супружеская пара, родитель-одиночка? Введите с маленькой буквы. '
Read_monthly_income2 = 'Далее введите свой месячный доход (в долларах США). '
p2 = 'один субъект'
f2 = 'супружеская пара'
sp2 = 'родитель-одиночка'
question2 = 'Каков ваш месячный доход за'

TaxError1 = 'Error! We can\'t calculate the tax! Please try again.'
TaxError2 = 'Ошибка! Мы не можем расчитать налог! Пожалуйста попробуйте снова.'
